### ISSUE TITLE
segmentation fault after 10 amino acids

### ISSUE THREAD

**Issue by thepineapplepirate** [danpf/pulchra#2]
Hi @danpf,

Have you run into a problem where the code quits with a segmentation fault after after a certain amount of amino acids. In my case, this starts happenning right at 10 amino acids. I'm using an alpha carbon output from a protein structure predictor. Attached is a sample file where this happens (had to save it as a txt since github wouldn't let me post a pdb file). Any insight would be much appreciated!
[test_Ca.txt](https://github.com/danpf/pulchra/files/10865676/test_Ca.txt)

**Comment by danpf** [comment]
Hi @thepineapplepirate 

I have not actually seen that before. : /  But the underlying pulchra algorithm makes some assumptions that your input CA trace is 'somewhat ok' -- That is most likely your problem because based on your input file, I think the CA trace is not at all close to physically realistic.

this is the output I get.

[test_CA_pypulchra.pdb.txt](https://github.com/danpf/pulchra/files/10867556/test_CA_pypulchra.pdb.txt)

**Comment by thepineapplepirate** [comment]
Hey @danpf , I suspected that was it. Bond lengths must be too small. Thanks for looking into that!

**Comment by danpf** [comment]
If you're just looking for simple visualization, In the past I've just used a static set of AA rotamers and just aligned the N & C to the prev CA and the next CA respectively.  Using conect records can also help with visualization

**Comment by thepineapplepirate** [comment]
Hi @danpf, quick question. Do you know if the code is designed to fail whenever it encounters a 180 degree angle between 3 consecutive alpha carbons (on a straight line)? In brief, I'm working with lattice models, and this new models can yield structures with segments having 180 degree angles.  I know that "nature doesn't occur in straight lines", but I wonder if programatically speaking, there is something in the code that would prevent this.

The error is a segmentation fault error, similar to what happens when you try to use pulchra on a structure with overlapping beads, or bonds that are too short. "**363410 Segmentation fault      (core dumped) pulchra ./structure_input.pdb -v**"

I'm including an image of an input structure just in case.  Appreciate any insight.

![180](https://github.com/user-attachments/assets/36bf1beb-3025-4b0d-a13c-af883eecb819)

**Comment by danpf** [comment]
Hi @thepineapplepirate
I haven't really used this code in a while, I'm not sure if there's anything that's a better solution for CA BB completion.

To be honest, I have forgotten most of what this code is doing but, I can maybe suggest 1 thing: 

Try building a small pilot app using the code found here: https://github.com/steineggerlab/foldseek/tree/master/lib/pulchra 
the steinegger lab has modified the underlying pulchra code and 'possibly?' made it more robust.  If it works well then it shouldn't be too hard to integrate with the code here to create a python interface for it.  Other than that I don't really have any advice for you :/

**Comment by thepineapplepirate** [comment]
Hi @danpf, ok no problem! Just figured I would ask just in case.  I appreciate the reference, I will take a look at their code at some point and go from there.  It's worked great for us so far, just wasn't sure if this was normal or not.  I did go through the code and I think this and line 899 might have something to do with it.  At first glance, it seems like this might end up in something being divided by zero, when you have a 180 angle:

https://github.com/danpf/pulchra/blob/1b7b92b8a7d29bc25290177ad5bab8fa2fbbe53f/src/cpp/pulchra.hpp#L884

Thanks!

**Comment by danpf** [comment]
I'm happy to accept a PR if you end up finding a solution that works for you and doesn't change too much !
